#!/bin/bash
#
# Append new notebooks for documentation in this file

buildrst DOC-geomutil.ipynb
buildrst DOC-LayoutEditor.ipynb
buildrst DOC-Mobility.ipynb
buildrst DOC-MultiwallAndCoverage.ipynb
buildrst DOC-RayTracing.ipynb
buildrst DOC-RGPA.ipynb
buildrst DOC-SlabAndMaterials.ipynb
buildrst DOC-UWBWaveform.ipynb
