#!/bin/bash
for i in *.html;
do 
cat $i | sed "s/notebook/\./g" > tmp
if [ $? -eq 0 ]
then 
mv tmp $i
echo $i
fi
done
cd $WEBNB/2-gis
./fixit
cd $WEBNB/3-antprop
./fixit
cd $WEBNB/4-signal
./fixit
cd $WEBNB/5-mobility
./fixit
cd $WEBNB/7-location
./fixit
cd $WEBNB/8-simul
./fixit
