from pylayers.gis.layout import  *
import matplotlib.pyplot as plt
L = Layout('exemple.str')
buildGt()
buildGr()
buildGv()
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(221)
fig,ax = showG('s',fig=fig,ax=ax)
tis = plt.title("Gs")
ax = fig.add_subplot(222)
fig,ax = showG('r',fig=fig,ax=ax)
tit = plt.title("Gt")
ax = fig.add_subplot(223)
fig,ax = showG('c',fig=fig,ax=ax)
tic = plt.title("Gc")
ax = fig.add_subplot(224)
fig,ax = showG('v',fig=fig,ax=ax)
tiv = plt.title("Gv")
plt.show()
