#!/bin/bash 
for i in *.ipynb;
do 
if [ -f  ${i%%.ipynb}.rst ]
then 
    echo ${i%%.ipynb}.rst    
    echo "deleting "  ${i%%.ipynb}.rst 
    rm ${i%%.ipynb}.rst 
fi
python $PYLAYERS/script/remove_output.py $i > tmp
if [ $? -eq 0 ]
then
    mv tmp $i
fi
done
