#!/usr/bin/python
import codecs
import sys
import os

if len(sys.argv)>1:
    filename = sys.argv[1]
    file = codecs.open(filename,"r",encoding="utf-8")
    data = file.read()
    filetemp = codecs.open("tempAscii","w",encoding="ascii",errors="ignore")
    filetemp.write(data)
    os.rename('tempAscii',filename)

