#!/bin/bash
for i in `find . -name "*.ipynb" | grep -v "checkpoints" | sort`;
do
    echo $i 
    #convert in rst 
    runipy -o $i
    ipython nbconvert --to rst $1
    # supress In[ ]
    cat ${1%%.ipynb}.rst | sed '/^In\[.*\]:/d' > f1
    # replace code with code-block
    cat f1 | sed 's/code::/code-block::/'  > f2 
    # link to images 
    cat f2 | sed "s/image:: /image:: ${1%%.ipynb}_files\//"  > ${1%%.ipynb}.rst
    #rm -Rf ../doc/notebooks/${1%%.ipynb}_files 
    #rm -Rf ../../website/html/notebooks/${1%%.ipynb}_files 
    #mv -f ${1%%.ipynb}.rst $PYLAYERS/doc/notebooks
    #cp -Rf ${1%%.ipynb}_files $PYLAYERS/doc/notebooks
    #mv -f ${1%%.ipynb}_files $WEBSITE/html/notebooks
    rm f1
    rm f2
done
