#!/bin/bash
# clean website 
#. $WEBNB/cleanfiles
# for all notebooks below

for i in `find . -name "*.ipynb" | grep -v "checkpoints" | sort`;
do
    # display filename
    # if rst file exists
    if [ -f ${i%%.ipynb}.rst ]; 
    then
           # rst file exists
           echo "${i%%.ipynb}.rst exists"
    else
            # regenerate out put cell 
           echo "run notebook",$i 
           runipy -o $i --pylab >>log 2>> log-err
    fi
    # if command successful
    if test ${?} -eq 0; 
    then
        file=`basename $i`
        echo $file
        # create rst file from notebook  
        ipython nbconvert --to rst $i >> log 2>>log-err 
        #ipython nbconvert --to mkd $i >> log 2>>log-err 
        # supress In[ ]
        cat ${file%%.ipynb}.rst | sed '/^In\[.*\]:/d' > f1
        # code --> code-block
        cat f1 | sed 's/code::/code-block::/'  > ${i%%.ipynb}.rst 
        # mv images in WEBNB directory
        mv -f ${file%%.ipynb}_files $WEBNB/${i%%.ipynb}_files 
        rm ${file%%.ipynb}.rst
        rm f1
    else
        echo "Problem in  ",$i
        exit
    fi     
    #rm f2
done
