#!/bin/bash 
for i in `find . -name "*.ipynb" | grep -v "checkpoints" | sort`;
do 
echo $i    
echo  ${i%%.ipynb}.rst
if [ $? -eq 0 ]
then 
    rm ${i%%.ipynb}.rst 
fi
python $PYLAYERS/script/remove_output.py $i > tmp
if [ $? -eq 0 ]
then
    mv tmp $i
fi
done
